// <auto-generated />
using System;
using API_EF_SQLite.CashFlow;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_EF_SQLite.Migrations
{
    [DbContext(typeof(CashFlowContext))]
    partial class CashFlowContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("API_EF_SQLite.CashFlow.Entities.CashFlowDAO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("CashFlow");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2023, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 0,
                            Value = 1000m
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2023, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 0,
                            Value = 1000m
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2023, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1,
                            Value = 900m
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2023, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 0,
                            Value = 1000m
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2023, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1,
                            Value = 2000m
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTime(2023, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1,
                            Value = 100m
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateTime(2023, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 0,
                            Value = 90m
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateTime(2023, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 0,
                            Value = 2000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
